### ISSUE TITLE
Unable to install deepL async on latest Python(3.11)

### ISSUE THREAD

**Issue by Warglaive** [ffreemt/deepl-tr-async#10]
I get the following error when I try to install **deepl-tr-async**. 
**I _assume the project is no longer supported?_**
`Collecting deepl-tr-async
  Using cached deepl_tr_async-0.0.5-py3-none-any.whl (19 kB)
Collecting absl-py<0.10.0,>=0.9.0 (from deepl-tr-async)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-mmpia33y\absl-py_9469b7f67c9c40efad8dfb5cb5d34170\setup.py", line 34, in <module>
          raise RuntimeError('Python version 2.7 or 3.4+ is required.')
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by ffreemt** [comment]
Yes, the project should be archived soon, mainly because the deepl site has a very strictly rate limited. Hence async for multiple simultaneous requests does not make too much sense.

But I'll take a look, looks like something in the setup.py or pyproject.toml is not properly set.
